import authRoute from './auth.routes.js';
import assureRoute from './cotations/assure.routes.js';
import cotationRoute from './cotations/cotation.routes.js';
import documentRoute from './cotations/document.routes.js';
import prestataireRoute from './cotations/prestataire.routes.js';
import vehiculeRoute from './cotations/vehicule.routes.js';
import activiteRoute from './settings/activite.routes.js';
import agenceRoute from './settings/agence.routes.js';
import capitauxRoute from './settings/capitaux.routes.js';
import energieRoute from './settings/energie.routes.js';
import franchiseRoute from './settings/franchise.routes.js';
import garantieRoute from './settings/garantie.routes.js';
import marqueRoute from './settings/marque.routes.js';
import modeleRoute from './settings/modele.routes.js';
import packRoute from './settings/pack.routes.js';
import primeRoute from './settings/prime.routes.js';
import professionRoute from './settings/profession.routes.js';
import qualiteRoute from './settings/qualite.routes.js';
import statutRoute from './settings/statut.routes.js';
import tageRoute from './settings/tage.routes.js';
import tdocumentRoute from './settings/tdocument.routes.js';
import tpuissanceRoute from './settings/tpuissance.routes.js';
import userRoute from './user.routes.js';

export default (router) => {
  router.use('/auth', authRoute());
  router.use('/statut', statutRoute());
  router.use('/user', userRoute());
  router.use('/cotation', cotationRoute());
  router.use('/prestataire', prestataireRoute());
  router.use('/vehicule', vehiculeRoute());
  router.use('/document', documentRoute());

  router.use('/assure', assureRoute());
  router.use('/agence', agenceRoute());
  router.use('/activite', activiteRoute());
  router.use('/capitaux', capitauxRoute());
  router.use('/energie', energieRoute());
  router.use('/franchise', franchiseRoute());
  router.use('/garantie', garantieRoute());
  router.use('/marque', marqueRoute());
  router.use('/modele', modeleRoute());
  router.use('/pack', packRoute());
  router.use('/prime', primeRoute());
  router.use('/profession', professionRoute());
  router.use('/qualite', qualiteRoute());
  router.use('/tage', tageRoute());
  router.use('/tdocument', tdocumentRoute());
  router.use('/tpuissance', tpuissanceRoute());
  return router;
};
